name: Mobile smoke tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Install Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.2.1'
          use-dotnet: false
          export-templates: true
      - name: Cache Android build
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('project/android/plugins/**/build.gradle') }}
      - name: Start emulator and run smoke test
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          target: google_apis
          script: ./scripts/ci/run_android_smoke.sh

  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: '4.2.1'
          use-dotnet: false
          export-templates: true
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Run smoke test
        run: ./scripts/ci/run_ios_smoke.sh
